name: Playwright Tests and Build
on:
 workflow_dispatch:
  # push:
  #   branches: [main, feature/Aditya-Kumar-Singh]
  # pull_request:
  #   branches: main   # Trigger on PRs to main branch

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest         # Set a timeout of 60 minutes for the job
    steps:
    - uses: actions/checkout@v4    # Step to check out the repository code

    - uses: actions/setup-node@v4  # Step to set up Node.js environment
      with:
        node-version: lts/*        # Install the latest LTS version of Node.js

    - name: Install dependencies
      run: npm ci                  # Use `npm ci` for clean, reproducible installation

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps            # Install Playwright browsers along with dependencies

    - name: Run Playwright Smoke tests
      run: npx playwright test --grep "@smoke"           # Run tests with the @smoke tag

    - name: Run Playwright Acceptance tests
      run: npx playwright test                           # Run all Playwright tests

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30

  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: test

    steps:
    - uses: actions/checkout@v4
            
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
            
    - name: Install dependencies
      run: npm ci
            
    - name: Build Docker Image
      run:  sudo docker build -t ${{ secrets.DOCKER_USERNAME }}/dockerized-playwright-e2e-tests .      

  push:
    name: Push Docker Image to Docker Hub
    runs-on: ubuntu-latest
    needs: build
          
    steps:
    - uses: actions/checkout@v4
            
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Use Docker Hub credentials stored as GitHub secrets
        password: ${{ secrets.DOCKER_PASSWORD }}  # Docker Hub password stored as a GitHub secret
      
    - name: Push Docker Image to Docker Hub
      run:  sudo docker push ${{ secrets.DOCKER_USERNAME }}/dockerized-playwright-e2e-tests:latest

  run:
    name: Run Docker Image
    runs-on: ubuntu-latest
    needs: push

    steps:
    - uses: actions/checkout@v4
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Use Docker Hub credentials stored as GitHub secrets
        password: ${{ secrets.DOCKER_PASSWORD }}  # Docker Hub password stored as a   

    - name: Run Docker Image
      run:  sudo docker run ${{ secrets.DOCKER_USERNAME }}/dockerized-playwright-e2e-tests  
