name: Test and Build

permissions:
  pull-requests: write

on:
  pull_request:
    branches:
      - main
      - dev
      - stg

jobs:
  test:
    name: Run Unit Tests and Coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests 
        run: |
          pytest . > results.txt
          cat results.txt
          echo "RESULT_OUTPUT<<EOF" >> $GITHUB_ENV
          cat results.txt  >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV          


      - name: Post comment to PR with results
        if: github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: Test Results
          message: |
            ```
            ${{ env.RESULT_OUTPUT }}
            ```          

  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: test
    if: github.event.pull_request.merged == true

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t your-dockerhub-user/sample-app:${{ github.sha }} .

      - name: Push Docker image
        run: docker push your-dockerhub-user/sample-app:${{ github.sha }}
